keys:
     telegram_token: '811544504:AAG0KVEUQvjlf4j_JQHI7y5VHlW2LALs6w0'

features:
    bing_search:
        enabled: true
        commands:
            - img
        safe_search: 'Off'
        search_depth: 10
        subscription_key: e210201a31ca461ab90ab9d6651cc503

    get_2ch_post:
        enabled: true
        commands:
            - 2ch

    dick:
        enabled: true
        commands:
            - dick
            - d
        mu: 15
        sigma: 3

    gelbooru_search:
        enabled: true
        commands:
            - gel

    gif:
        enabled: true
        commands: 
            - gif
        path: userdata/mp4/

    glitch:
        enabled: true
        commands: 
            - glitch
        path: userdata/glitch/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp 
            - .webp

    google_search:
        enabled: false
        commands_image: 
            - img
        commands_video: 
            - vid
        google_dev_key: =====key=====
        google_cse_id: =====key=====

    graphs:
        enabled: true
        commands_activity:
         - activity
        commands_usage:
         - usage
        db_path: userdata/
        path: userdata/graphs/
        graph_logo: resources/graph_logo.jpg

    instagram:
        enabled: false
        commands: 
            - instagram
            - ig
        path: userdata/instagram/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp 
            - .webp
            - .svg
            - .mp4
            - .gif

    jpeg:
        enabled: true
        commands:
            - jpeg
        path: userdata/jpeg/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .webp

    kek:
        enabled: true
        commands: 
            - kek
        path: userdata/kek/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .webp

    leetspeak:
        enabled: true
        commands: 
            - leet
        leet_dictionary: resources/leetdict.txt

    lego:
        enabled: true
        commands: 
            - lego
        path: userdata/lego/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .bmp
            - .gif
            - .webp

    liquid:
        enabled: false
        commands: 
            - liq
        path: userdata/liquid/

    logging:
        enabled: true
        path: userdata/

    meme:
        enabled: true
        commands: 
            - meme
            - memos
        path: userdata/meme/
        fonts:
            impact:
                name: impact
                path: resources/fonts/impact.ttf
            lobster:
                name: lobster
                path: resources/fonts/lobster.ttf
            comic:
                name: comic
                path: resources/fonts/comic.ttf
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp

    nya:
        enabled: true
        commands: 
            - nya
        path: userdata/nya/
        
    palette:
        enabled: true
        commands:
            - palette
            - colors
        path:
            userdata/palette/
        extensions:
            - .jpg
            - .jpeg
            - .png
            - .webp
            - .bmp
            - .gif

    pcstat:
        enabled: true
        commands: 
            - status

    rate:
        enabled: true
        commands:
            - rate

    roll:
        enabled: true
        commands:
            - roll

    sticker_reply:
        enabled: true
        sticker_path: resources/kappa.webp
        keywords:
            - Kappa

    track:
        enabled: true
        commands:
            - track
            - subscribe
        path: userdata/

    toribash:
        enabled: false
        commands: 
            - toribash

    tts:
        enabled: true
        commands: 
            - say
        path: userdata/tts/

    vk:
        enabled: false
        commands: 
            - vk
        path: userdata/vk/
        channel: your_channel
        vk_token: =====key=====
        database: resources/whatever

    yandere_search:
        enabled: true
        commands: 
            - a
            - yandere
        path: userdata/yandere/
        
    zalgo:
        enabled: true
        commands:
            - zalgo
